### ISSUE TITLE
Auto select the message thing somewhere or something.

### ISSUE THREAD

**Issue by perryprog** [Union-Chat/union-website#10]

**Comment by devoxin** [comment]
Tfw I've only just noticed you've marked your own issue as `good first issue`. Wow.

**Comment by perryprog** [comment]
Smh that's normal

Also not really sure what this issue is for, unless it's for auto selecting the message input bar whenever you press a key.

**Comment by devoxin** [comment]
Oh I fixed that ages ago lol. Will close.
