### ISSUE TITLE
Client/server side message cache

### ISSUE THREAD

**Issue by xXBuilderBXx** [Union-Chat/union-website#11]
Would be nice to have some kind of message cache so that we can switch servers without having the messages cleared when you switch back to that server.

**Comment by devoxin** [comment]
Best I can offer at the moment would be a client-side cache which would store all messages internally, but won't persist across page-reloads.

**Comment by devoxin** [comment]
Client-side message caching was implemented in 06041a0645d6da11fad377c075abaf8c18742202
