### ISSUE TITLE
Unread message indicators 

### ISSUE THREAD

**Issue by perryprog** [Union-Chat/union-website#12]
When looking at another server it's currently impossible to tell if any other servers have received messages without clicking them. A discord style unread indicator would be helpful.

Possible styles:
- Number of unread messages in a circle, changing color if you're mentioned
- Number of unread messages in a circle, with a second circle with the number of times you've been mentioned
- A dot if there's any unread messages, with a number in it if you're mentioned 
- A dot if there's any unread messages, changing color if you're mentioned

**Comment by devoxin** [comment]
Good idea. Will consider.

**Comment by devoxin** [comment]
Added in 95afb1c2555f9ecb66ba9e3bc666a17b6ee5dbee
